name: Sync-changes-to-HF

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: True
      - name: LFS Install
        run: git lfs install
      - name: LFS Track
        run: git lfs track *.jpg
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: reset commit
        run: git filter-branch --force --index-filter "git rm --cached --ignore-unmatch sdlc_complete_workflow.png" --prune-empty --tag-name-filter cat -- --all

      - name: reset commit-2
        run: git filter-branch --force --index-filter "git rm --cached --ignore-unmatch notebooks/sdlc_workflow.png" --prune-empty --tag-name-filter cat -- --all

      - name: reset commit-3
        run: git filter-branch --force --index-filter "git rm --cached --ignore-unmatch workflow.jpeg" --prune-empty --tag-name-filter cat -- --all

      - name: reset commit-4
        run: git filter-branch --force --index-filter "git rm --cached --ignore-unmatch notebooks/sdlc_workflow.png" --prune-empty --tag-name-filter cat -- --all

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://shubhamprajapati7748:$HF_TOKEN@huggingface.co/spaces/shubhamprajapati7748/sdlc-copilot main
